{"name": "Login with invalid credential", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: ''\n", "trace": "  File \"C:\\Users\\This PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\This PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert error_message in [\"User not found\", \"Unauthorized\"], f\"Unexpected error message: '{error_message}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1745686924670, "stop": 1745686943722}, {"name": "When I enter invalid email and password", "status": "passed", "start": 1745686943722, "stop": 1745686944007}, {"name": "And I click the login button", "status": "passed", "start": 1745686944007, "stop": 1745686944085}, {"name": "Then I should see an error message", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected error message: ''\n", "trace": "  File \"C:\\Users\\This PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\This PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 49, in step_impl\n    assert error_message in [\"User not found\", \"Unauthorized\"], f\"Unexpected error message: '{error_message}'\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1745686944085, "stop": 1745686954496}], "start": 1745686924670, "stop": 1745686954497, "uuid": "f2f34200-fdda-4344-b5dc-7449c995011a", "historyId": "ae4df6ee936a023f095771dd1d458ea2", "fullName": "Login functionality on Sailor website: Login with invalid credential", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login functionality on Sailor website"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}